name: goreleaser

on:
  push:
    tags:
      - '*'

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Unshallow
        run: git fetch --prune --unshallow
      -
        name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.13.x
      -
        name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v1
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  dockerbuild:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout code
        uses: actions/checkout@v2

      -
        name: Get the pushed tag
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF/refs\/tags\//}

      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v1
        with:
          push: true
          registry: covermymeds.azurecr.io
          username: ${{ secrets.service_principal }}
          password: ${{ secrets.service_principal_password }}
          repository: cmm/azure-key-vault-agent
          tags: ${{ steps.vars.outputs.tag }}
